language: node_js
node_js:
  - lts/dubnium
  - node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: M010Bqwf/yFK47AXo2enTSJwyJ9YmISV6y9p1N3OkyNQ1nHuMolbF0+p4kN3VG2QebRvALlY8DsbC1+Xtv9nnqqWgE4zUplGvwbaGvmL7eOTk0Wdtt18L+qqm3syrlcfzZLwISmGLEQ/oZArDcPQCUtZrAW4YY5q43Vqf6EDMYZDVkCF5ppr+q2Byciqlkwo8xg6njfKbhSVqLJI/zwGjHcaOGdBSyOzHr9oWT3hmjkGn/3Xz/kHQvCnrVN5wW9wDb++gSSiEyBA9s1EhFM0V1I1tzlHafekh39ppRq802HwnW9qQ46+AcJgEIodbo0SwfK7Qp54EBtBtPlsEVUXNTtDYMXDDXRreKjt39yK12cw5KLYLpYP3utxHPFHoc1F/JED1TEpyEEaV2N8HPgwaJ03ZjMcAT5EgL11J8AyeGVMAVJmNdaJgvedo8fzCOSIz83AgXcHw5I7/GVDU11okMCnZUt+mG0k1KcTcuneQU5Px0+0VEawAoj2xJ+FRxUhfCUNBCLZUsaCt7cLuI1U/o+KUGNFe1TNMkRmm/Mb2g6jCEZuWvWOIFm8yHMYHMRJ1wP/lPFyqrAyQLQjzLSHpAW7reqbWAbyc+gu2+voUEcRlTKmCdzZfDrKihQpfnyT99XXH+Pbq8PqAb1ifihPO7uaEIMDWkwTRM7bNF43F+4=
  file:
    - 'mathml-tag-names.js'
    - 'mathml-tag-names.min.js'
  on:
    tags: true
